{
 "title": "Flash sale dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top Selling Products (Last Hour)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  p.name as \"Product\",\n  COUNT(o.id) as \"Orders\",\n  SUM(o.quantity) as \"Units Sold\",\n  CONCAT('$', ROUND(SUM(o.total_amount)::numeric, 2)) as \"Revenue\",\n  p.stock_level as \"Stock Left\"\nFROM orders o\nJOIN products p ON o.product_id = p.id\nWHERE o.order_time > NOW() - INTERVAL '1 hour'\nGROUP BY p.id, p.name, p.stock_level\nORDER BY SUM(o.total_amount) DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Total Inventory Value",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(stock_level * price) as value,\n  'Inventory Value' as metric\nFROM products"
    }
   ]
  },
  {
   "title": "Stock Level Comparison",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  name as metric,\n  stock_level as value\nFROM products\nORDER BY stock_level ASC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Critical Products count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as value FROM products WHERE stock_level <= 5"
    }
   ]
  },
  {
   "title": "Low Product count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as value FROM products WHERE stock_level <= low_stock_threshold"
    }
   ]
  },
  {
   "title": "Gamin Laptop count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  stock_level as value,\n  'Gaming Laptop' as metric\nFROM products \nWHERE id = 1"
    }
   ]
  },
  {
   "title": "Order volume over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"api-service\", endpoint=\"/api/orders\", status=~\"20.\"}[1m])) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"api-service\", endpoint=\"/api/orders\", status=\"400\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('minute', order_time) as time,\n  SUM(total_amount) as value,\n  'Revenue' as metric\nFROM orders \nWHERE order_time > NOW() - INTERVAL '1 hour'\nGROUP BY DATE_TRUNC('minute', order_time)\nORDER BY time ASC"
    }
   ]
  }
 ]
}